<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="SecureFact.Security.Tests" />
    <InternalsVisibleTo Include="SecureFact.Unit.Tests" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <ProjectReference Include="..\..\..\SecureFact.SharedKernel\SecureFact.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\SecureFact.Platform\SecureFact.Platform.csproj" />
    <ProjectReference Include="..\SecureFact.Notifications.Contracts\SecureFact.Notifications.Contracts.csproj" />
    <ProjectReference Include="..\..\Identity\SecureFact.Identity.Contracts\SecureFact.Identity.Contracts.csproj" />
    <ProjectReference Include="..\..\Tenancy\SecureFact.Tenancy.Contracts\SecureFact.Tenancy.Contracts.csproj" />
  </ItemGroup>
</Project>
