<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
    <ProjectReference Include="..\SecureFact.SharedKernel\SecureFact.SharedKernel.csproj" />
    <ProjectReference Include="..\SecureFact.Platform\SecureFact.Platform.csproj" />
    <ProjectReference Include="..\Modules\Tenancy\SecureFact.Tenancy\SecureFact.Tenancy.csproj" />
    <ProjectReference Include="..\Modules\Audit\SecureFact.Audit\SecureFact.Audit.csproj" />
    <ProjectReference Include="..\Modules\Organizations\SecureFact.Organizations\SecureFact.Organizations.csproj" />
    <ProjectReference Include="..\Modules\Billing\SecureFact.Billing\SecureFact.Billing.csproj" />
    <ProjectReference Include="..\Modules\TaxEngine\SecureFact.TaxEngine\SecureFact.TaxEngine.csproj" />
    <ProjectReference Include="..\Modules\Catalogs\SecureFact.Catalogs\SecureFact.Catalogs.csproj" />
    <ProjectReference Include="..\Modules\CpeEngine\SecureFact.CpeEngine\SecureFact.CpeEngine.csproj" />
    <ProjectReference Include="..\Modules\Rules\SecureFact.Rules\SecureFact.Rules.csproj" />
    <ProjectReference Include="..\Modules\Customers\SecureFact.Customers\SecureFact.Customers.csproj" />
    <ProjectReference Include="..\Modules\Certificates\SecureFact.Certificates\SecureFact.Certificates.csproj" />
    <ProjectReference Include="..\Modules\Products\SecureFact.Products\SecureFact.Products.csproj" />
    <ProjectReference Include="..\Modules\Identity\SecureFact.Identity\SecureFact.Identity.csproj" />
  </ItemGroup>
</Project>
