// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecureFact.Tenancy.Infrastructure;

#nullable disable

namespace SecureFact.Tenancy.Infrastructure.Migrations
{
    [DbContext(typeof(TenancyDbContext))]
    partial class TenancyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tenancy")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecureFact.Tenancy.Domain.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowsOverage")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_overage");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxCompanies")
                        .HasColumnType("integer")
                        .HasColumnName("max_companies");

                    b.Property<int?>("MaxDocumentsPerMonth")
                        .HasColumnType("integer")
                        .HasColumnName("max_documents_per_month");

                    b.Property<int?>("MaxUsers")
                        .HasColumnType("integer")
                        .HasColumnName("max_users");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ResellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reseller_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("plan", "tenancy");
                });

            modelBuilder.Entity("SecureFact.Tenancy.Domain.Reseller", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BrandName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("brand_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Host")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("host");

                    b.Property<DateTimeOffset?>("HostCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("host_checked_at");

                    b.Property<string>("HostError")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("host_error");

                    b.Property<int>("HostFailures")
                        .HasColumnType("integer")
                        .HasColumnName("host_failures");

                    b.Property<string>("HostStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("host_status");

                    b.Property<string>("HostToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("host_token");

                    b.Property<DateTimeOffset?>("HostVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("host_verified_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("bytea")
                        .HasColumnName("logo");

                    b.Property<string>("LogoContentType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("logo_content_type");

                    b.Property<string>("LogoVersion")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("logo_version");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("primary_color");

                    b.Property<string>("SupportEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("support_email");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Host")
                        .IsUnique()
                        .HasDatabaseName("ux_reseller_host")
                        .HasFilter("host IS NOT NULL");

                    b.ToTable("reseller", "tenancy");
                });

            modelBuilder.Entity("SecureFact.Tenancy.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("environment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("PlanAssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("plan_assigned_at");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateTimeOffset?>("ResellerAssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reseller_assigned_at");

                    b.Property<Guid?>("ResellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reseller_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SuspendedBy")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("suspended_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("tenant", "tenancy");
                });
#pragma warning restore 612, 618
        }
    }
}
