// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecureFact.Subscriptions.Infrastructure;

#nullable disable

namespace SecureFact.Subscriptions.Infrastructure.Migrations
{
    [DbContext(typeof(SubscriptionsDbContext))]
    [Migration("20261009183655_AddInvoicing")]
    partial class AddInvoicing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("subscription")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecureFact.Subscriptions.Domain.BillingPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DueDays")
                        .HasColumnType("integer")
                        .HasColumnName("due_days");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("note");

                    b.Property<int?>("SuspendAfterDays")
                        .HasColumnType("integer")
                        .HasColumnName("suspend_after_days");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveFrom")
                        .IsUnique();

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("billing_policy", "subscription");
                });

            modelBuilder.Entity("SecureFact.Subscriptions.Domain.BillingProfile", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("document_number");

                    b.Property<string>("DocumentTypeCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("document_type_code");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("TenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("billing_profile", "subscription");
                });

            modelBuilder.Entity("SecureFact.Subscriptions.Domain.Charge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CommissionScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("commission_schedule_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int>("DocumentsIssued")
                        .HasColumnType("integer")
                        .HasColumnName("documents_issued");

                    b.Property<DateOnly>("DueOn")
                        .HasColumnType("date")
                        .HasColumnName("due_on");

                    b.Property<int?>("IncludedDocuments")
                        .HasColumnType("integer")
                        .HasColumnName("included_documents");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<decimal>("MonthlyFee")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("monthly_fee");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("net_amount");

                    b.Property<decimal>("OverageAmount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("overage_amount");

                    b.Property<int>("OverageDocuments")
                        .HasColumnType("integer")
                        .HasColumnName("overage_documents");

                    b.Property<decimal?>("OverageUnitPrice")
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("overage_unit_price");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date")
                        .HasColumnName("period");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("plan_code");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("plan_name");

                    b.Property<Guid>("PriceId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_id");

                    b.Property<Guid?>("ResellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reseller_id");

                    b.Property<DateOnly?>("SuspendOn")
                        .HasColumnType("date")
                        .HasColumnName("suspend_on");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("tax_rate");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tenant_name");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_amount");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("void_reason");

                    b.Property<DateTimeOffset?>("VoidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at");

                    b.HasKey("Id");

                    b.HasIndex("DueOn");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Period")
                        .IsUnique();

                    b.ToTable("charge", "subscription");
                });

            modelBuilder.Entity("SecureFact.Subscriptions.Domain.ChargeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("charge_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("DocumentTypeCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("document_type_code");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<Guid>("IssuerTenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("issuer_tenant_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<long>("Number")
                        .HasColumnType("bigint")
                        .HasColumnName("number");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("series");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("ChargeId", "Kind")
                        .IsUnique();

                    b.ToTable("charge_document", "subscription");
                });

            modelBuilder.Entity("SecureFact.Subscriptions.Domain.CommissionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("base_amount");

                    b.Property<Guid>("ChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("charge_id");

                    b.Property<DateOnly>("ChargePeriod")
                        .HasColumnType("date")
                        .HasColumnName("charge_period");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date")
                        .HasColumnName("month");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("rate");

                    b.Property<Guid>("ResellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reseller_id");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tenant_name");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.HasIndex("ResellerId", "Month");

                    b.ToTable("commission_entry", "subscription");
                });

            modelBuilder.Entity("SecureFact.Subscriptions.Domain.CommissionSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("note");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveFrom")
                        .IsUnique();

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("commission_schedule", "subscription");
                });

            modelBuilder.Entity("SecureFact.Subscriptions.Domain.CommissionSettlement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Entries")
                        .HasColumnType("integer")
                        .HasColumnName("entries");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date")
                        .HasColumnName("month");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("note");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<Guid>("ResellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reseller_id");

                    b.Property<DateOnly>("SettledOn")
                        .HasColumnType("date")
                        .HasColumnName("settled_on");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("ResellerId", "Month")
                        .IsUnique();

                    b.ToTable("commission_settlement", "subscription");
                });

            modelBuilder.Entity("SecureFact.Subscriptions.Domain.CommissionTier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("MinAccounts")
                        .HasColumnType("integer")
                        .HasColumnName("min_accounts");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("rate");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId", "MinAccounts")
                        .IsUnique();

                    b.ToTable("commission_tier", "subscription");
                });

            modelBuilder.Entity("SecureFact.Subscriptions.Domain.InvoicingSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<Guid>("InvoiceNoteSeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_note_series_id");

                    b.Property<Guid>("InvoiceSeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_series_id");

                    b.Property<Guid>("IssuerTenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("issuer_tenant_id");

                    b.Property<Guid>("ReceiptNoteSeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_note_series_id");

                    b.Property<Guid>("ReceiptSeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_series_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("invoicing_settings", "subscription");
                });

            modelBuilder.Entity("SecureFact.Subscriptions.Domain.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("charge_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("method");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("note");

                    b.Property<DateOnly>("PaidOn")
                        .HasColumnType("date")
                        .HasColumnName("paid_on");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<Guid?>("ReversesPaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_payment_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ChargeId");

                    b.HasIndex("ReversesPaymentId")
                        .IsUnique()
                        .HasFilter("reverses_payment_id IS NOT NULL");

                    b.HasIndex("TenantId");

                    b.ToTable("payment", "subscription");
                });

            modelBuilder.Entity("SecureFact.Subscriptions.Domain.PlanPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<int?>("IncludedDocuments")
                        .HasColumnType("integer")
                        .HasColumnName("included_documents");

                    b.Property<decimal>("MonthlyFee")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("monthly_fee");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("note");

                    b.Property<decimal?>("OverageUnitPrice")
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("overage_unit_price");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "EffectiveFrom")
                        .IsUnique();

                    b.HasIndex("PlanId", "Version")
                        .IsUnique();

                    b.ToTable("plan_price", "subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
