using System.Reflection;
using System.Text.Json;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
using SecureFact.Catalogs.Domain;
using SecureFact.Catalogs.Infrastructure;

namespace SecureFact.Catalogs.Application;

/// <summary>
/// Loads the catalogue seed generated by <c>tools/SecureFact.CatalogImporter</c> from SUNAT's validation-rules workbook (S16).
/// Idempotent: an edition whose source SHA-256 is already loaded is skipped; a new source becomes version N+1, effective from the
/// workbook date, and closes the previous version the day before. The first edition has no published start date, so it is effective
/// from <see cref="Baseline"/>.
/// </summary>
internal static partial class CatalogSeeder
{
    public const string ResourceName = "SecureFact.Catalogs.Seeds.sunat-catalogs-2026-08-26.json";

    /// <summary>"Since always": the source does not publish when each code became effective.</summary>
    public static readonly DateOnly Baseline = new(1900, 1, 1);

    private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.General);

    [GeneratedRegex(@"(\d{4})-(\d{2})-(\d{2})")]
    private static partial Regex DateInName();

    internal sealed record SeedEntry(string Code, string Description, Dictionary<string, string> Extra);

    internal sealed record SeedCatalog(string Number, string Name, List<string> Headers, List<SeedEntry> Entries);

    internal sealed record SeedSource(string File, long Bytes, string Sha256, string Sheet);

    internal sealed record SeedFile(SeedSource Source, List<SeedCatalog> Catalogs);

    internal static SeedFile LoadEmbedded()
    {
        using var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(ResourceName)
            ?? throw new InvalidOperationException($"Embedded resource {ResourceName} not found.");
        return JsonSerializer.Deserialize<SeedFile>(stream, Json) ?? throw new InvalidDataException("Catalogue seed is empty.");
    }

    /// <returns>Number of catalogue editions loaded (0 when everything was already present).</returns>
    public static async Task<int> SeedAsync(CatalogsDbContext db, TimeProvider clock, CancellationToken cancellationToken, SeedFile? source = null)
    {
        var seed = source ?? LoadEmbedded();
        var workbookDate = DateInName().Match(seed.Source.File) is { Success: true } m
            ? new DateOnly(int.Parse(m.Groups[1].Value, System.Globalization.CultureInfo.InvariantCulture), int.Parse(m.Groups[2].Value, System.Globalization.CultureInfo.InvariantCulture), int.Parse(m.Groups[3].Value, System.Globalization.CultureInfo.InvariantCulture))
            : Baseline;
        var loaded = 0;

        foreach (var catalog in seed.Catalogs)
        {
            if (await db.Editions.AnyAsync(e => e.CatalogNumber == catalog.Number && e.SourceSha256 == seed.Source.Sha256, cancellationToken))
            {
                continue;
            }

            var previous = await db.Editions.Where(e => e.CatalogNumber == catalog.Number).OrderByDescending(e => e.Version).FirstOrDefaultAsync(cancellationToken);
            var version = (previous?.Version ?? 0) + 1;
            var effectiveFrom = previous is null ? Baseline : workbookDate;

            if (previous is not null)
            {
                var closing = effectiveFrom.AddDays(-1);
                previous.EffectiveTo = closing;
                await db.Entries.Where(e => e.CatalogNumber == catalog.Number && e.Version == previous.Version && e.EffectiveTo == null)
                    .ExecuteUpdateAsync(s => s.SetProperty(e => e.EffectiveTo, closing), cancellationToken);
            }

            db.Editions.Add(new CatalogEdition
            {
                Id = Guid.CreateVersion7(),
                CatalogNumber = catalog.Number,
                Name = catalog.Name,
                Version = version,
                Source = seed.Source.File,
                SourceSha256 = seed.Source.Sha256,
                EffectiveFrom = effectiveFrom,
                LoadedAt = clock.GetUtcNow(),
            });

            foreach (var entry in catalog.Entries.DistinctBy(e => e.Code, StringComparer.Ordinal))
            {
                db.Entries.Add(new CatalogEntry
                {
                    Id = Guid.CreateVersion7(),
                    CatalogNumber = catalog.Number,
                    Code = entry.Code.Length > 60 ? entry.Code[..60] : entry.Code,
                    Description = entry.Description.Length > 1000 ? entry.Description[..1000] : entry.Description,
                    Version = version,
                    EffectiveFrom = effectiveFrom,
                    Source = seed.Source.File,
                    Active = true,
                    MetadataJson = JsonSerializer.Serialize(entry.Extra),
                });
            }

            loaded++;
        }

        await db.SaveChangesAsync(cancellationToken);
        return loaded;
    }
}
