<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <Using Include="Xunit" />
    <ProjectReference Include="..\..\..\src\SecureFact.Platform\SecureFact.Platform.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Tenancy\SecureFact.Tenancy\SecureFact.Tenancy.csproj" />
    <ProjectReference Include="..\..\..\src\SecureFact.Api\SecureFact.Api.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Identity\SecureFact.Identity\SecureFact.Identity.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Audit\SecureFact.Audit\SecureFact.Audit.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Customers\SecureFact.Customers\SecureFact.Customers.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Certificates\SecureFact.Certificates\SecureFact.Certificates.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\CpeEngine\SecureFact.CpeEngine\SecureFact.CpeEngine.csproj" />
    <ProjectReference Include="..\..\..\src\SecureFact.Workers\SecureFact.Workers.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Products\SecureFact.Products\SecureFact.Products.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Rules\SecureFact.Rules\SecureFact.Rules.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Catalogs\SecureFact.Catalogs\SecureFact.Catalogs.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Billing\SecureFact.Billing\SecureFact.Billing.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Organizations\SecureFact.Organizations\SecureFact.Organizations.csproj" />
  </ItemGroup>
</Project>
