<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="SecureFact.Security.Tests" />
    <InternalsVisibleTo Include="SecureFact.Unit.Tests" />
    <EmbeddedResource Include="Seeds\sunat-catalogs-2026-08-26.json" LogicalName="SecureFact.Catalogs.Seeds.sunat-catalogs-2026-08-26.json" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <ProjectReference Include="..\..\..\SecureFact.SharedKernel\SecureFact.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\SecureFact.Platform\SecureFact.Platform.csproj" />
    <ProjectReference Include="..\SecureFact.Catalogs.Contracts\SecureFact.Catalogs.Contracts.csproj" />
  </ItemGroup>
</Project>
