<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <Using Include="Xunit" />
    <ProjectReference Include="..\..\..\src\SecureFact.SharedKernel\SecureFact.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\src\SecureFact.Platform\SecureFact.Platform.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Identity\SecureFact.Identity\SecureFact.Identity.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Audit\SecureFact.Audit\SecureFact.Audit.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Notifications\SecureFact.Notifications\SecureFact.Notifications.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Gre\SecureFact.Gre\SecureFact.Gre.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\TaxEngine\SecureFact.TaxEngine\SecureFact.TaxEngine.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\CpeEngine\SecureFact.CpeEngine\SecureFact.CpeEngine.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Catalogs\SecureFact.Catalogs\SecureFact.Catalogs.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Billing\SecureFact.Billing\SecureFact.Billing.csproj" />
    <ProjectReference Include="..\..\..\tools\SecureFact.CatalogImporter\SecureFact.CatalogImporter.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Rules\SecureFact.Rules\SecureFact.Rules.csproj" />
  </ItemGroup>
</Project>
