// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecureFact.Catalogs.Infrastructure;

#nullable disable

namespace SecureFact.Catalogs.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogsDbContext))]
    [Migration("20261001143445_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecureFact.Catalogs.Domain.CatalogEdition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CatalogNumber")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("catalog_number");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<DateTimeOffset>("LoadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source");

                    b.Property<string>("SourceSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("source_sha256")
                        .IsFixedLength();

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CatalogNumber", "SourceSha256")
                        .IsUnique();

                    b.HasIndex("CatalogNumber", "Version")
                        .IsUnique();

                    b.ToTable("catalog_edition", "catalog");
                });

            modelBuilder.Entity("SecureFact.Catalogs.Domain.CatalogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("CatalogNumber")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("catalog_number");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CatalogNumber", "EffectiveFrom");

                    b.HasIndex("CatalogNumber", "Code", "Version")
                        .IsUnique();

                    b.ToTable("catalog_entry", "catalog");
                });
#pragma warning restore 612, 618
        }
    }
}
